Models/ErrorViewModel.cs
namespace InstagramAPI.Models;

public class ErrorViewModel
{
    public string RequestId { get; set; }
    public string ErrorMessage { get; set; }
    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using InstagramAPI.Models;

namespace InstagramAPI.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/InstagramController.cs
using Microsoft.AspNetCore.Mvc;

namespace InstagramAPI.Controllers;

public class InstagramController : Controller
{
    private readonly InstagramService _instagramService;

    public InstagramController(InstagramService instagramService)
    {
        _instagramService = instagramService;
    }

    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }
    [HttpPost]
    public async Task<ActionResult> Index(string userName)
    {
        string userInfoUrl = "https://igs.sf-converter.com/api/userInfoByUsername/";
        string userId = await _instagramService.GetUserIdAsync(userInfoUrl, userName);
        string userStoriesUrl = "https://igs.sf-converter.com/api/stories/" + userId;
        var videos = await _instagramService.GetUserStoriesAsync(userStoriesUrl);
        return RedirectToAction("ShowVideos", new { videoUrls = videos });
    }

    public ActionResult ShowVideos(IEnumerable<string> videoUrls)
    {
        return View(videoUrls);
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Instagram/Index.cshtml
@{
    ViewBag.Title = "Enter Instagram Username";
}

<h2>@ViewBag.Title</h2>

<form action="/Instagram/Index" method="post">
    <label for="userName">Instagram Username:</label>
    <input type="text" id="userName" name="userName" required />
    <input type="submit" value="Get Videos" />
</form>

Views/Instagram/ShowVideos.cshtml
@model IEnumerable<string>
@{
    ViewBag.Title = "Instagram Videos";
    var videoUrls = Model;
}

<h2>@ViewBag.Title</h2>

<style>
    #contentWrapper {
        display: grid;
        grid-template-columns: repeat(auto-fill, minmax(360px, 1fr));
        gap: 20px;
        justify-content: center;
    }

    .videoPlayer {
        width: 360px;
    }

    .videoElement {
        width: 100%;
        height: 640px;
    }
</style>

@if (videoUrls != null && videoUrls.Any())
{
    <div id="contentWrapper">
        @{
            foreach (var videoUrl in videoUrls)
            {
                <div class="videoPlayer">
                    <video id="videoElement@counter" class="videoElement" controls muted>
                        <source src="@videoUrl" type="video/mp4">
                        Ваш браузер не поддерживает элемент <code>video</code>.
                    </video>
                </div>
            }
        }
    </div>
}
else
{
    <p>No videos found for the given username.</p>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - InstagramAPI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/InstagramAPI.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InstagramAPI</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Instagram" asp-action="Index">InstagramAPI</a>
                        </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - InstagramAPI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>